In [1]:
#1
import numpy as np
vector = np.arange(1,11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#2
matrix =np.zeros((3,3))
print(matrix)

[[0.8602117  0.54477625 0.59986449 0.6538762 ]
 [0.2307966  0.10551947 0.41417331 0.65860848]
 [0.40035488 0.12900614 0.69750305 0.87625593]
 [0.17621728 0.72155751 0.12970914 0.37917489]]


In [11]:
#3
matrix = np.random.randint(1, 11, size=(5, 5))
print(matrix)

[[ 7  8  9  6  4]
 [ 8  3  3  2 10]
 [ 7  5  5  1  1]
 [ 9  1  4  2  4]
 [ 9  2  8  9  8]]


In [5]:
#4
matrix = np.random.random((4, 4))
print(matrix)

[[0.8602117  0.54477625 0.59986449 0.6538762 ]
 [0.2307966  0.10551947 0.41417331 0.65860848]
 [0.40035488 0.12900614 0.69750305 0.87625593]
 [0.17621728 0.72155751 0.12970914 0.37917489]]


In [7]:
#5
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print(array1)
print(array2)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)

[4 8 6 6 4]
[ 3  3 10  3  6]
Addition: [ 7 11 16  9 10]
Subtraction: [ 1  5 -4  3 -2]
Multiplication: [12 24 60 18 24]


In [8]:
#6
vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector2 = np.array([7, 6, 5, 4, 3, 2, 1])

print(vector1)
print(vector2)
dot_product = np.dot(vector1, vector2)
print("Dot Product:", dot_product)

Dot Product: 84


In [12]:
#7
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

matrix_product = np.dot(matrix1, matrix2)
print(matrix_product)

[[52 68 18]
 [52 46 55]]


In [13]:
#8
matrix = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix)

print("Matrix:")
print(matrix)
print("Inverse Matrix:")
print(inverse_matrix)

Matrix:
[[ 9  1 10]
 [ 8  8  8]
 [ 6  7  2]]
Inverse Matrix:
[[ 0.16129032 -0.27419355  0.29032258]
 [-0.12903226  0.16935484 -0.03225806]
 [-0.03225806  0.22983871 -0.25806452]]


In [18]:
#9
matrix = np.random.random((4,4))
matrix_t = matrix.T
print(matrix)
print(matrix_t)

[[0.60733251 0.29148219 0.10039797 0.63291391]
 [0.28840092 0.15089549 0.20716884 0.75645424]
 [0.33944374 0.28335502 0.81959594 0.49220486]
 [0.9500101  0.70955406 0.45602905 0.89332232]]
[[0.60733251 0.28840092 0.33944374 0.9500101 ]
 [0.29148219 0.15089549 0.28335502 0.70955406]
 [0.10039797 0.20716884 0.81959594 0.45602905]
 [0.63291391 0.75645424 0.49220486 0.89332232]]


In [20]:
#10
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)

matrix_vector_product = np.dot(matrix, vector)
print(matrix_vector_product)

[184 147 175]


In [21]:
#11
matrix = np.random.random((2,3))
vector = np.random.random(3)

matrix_vector_product = np.dot(matrix, vector)
print(matrix_vector_product)

[0.77355559 0.83391122]


In [23]:
#12
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 2))

matrix_matrix_product = np.multiply(matrix_1, matrix_2)
print(matrix_matrix_product)

[[28  4]
 [30 25]]


In [24]:
#13
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 2))

matrix_matrix_product = np.dot(matrix_1, matrix_2)
print(matrix_matrix_product)

[[ 91 101]
 [105 111]]


In [26]:
#14
matrix = np.random.randint(1, 101, size=(5, 5))
sum_of_elements = np.sum(matrix)
print("Matrix:")
print(matrix)
print("Sum of Elements:", sum_of_elements)

Matrix:
[[37 80 11 88 37]
 [53 91 85 25 77]
 [83 78 91 89 67]
 [23 19 33 69 34]
 [11 44 64 33 38]]
Sum of Elements: 1360


In [28]:
#15
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

difference = matrix1 - matrix2
print(difference)


[[-1  4 -5  1]
 [ 0 -1  0 -1]
 [-3  4 -1  3]
 [-1 -2  5  2]]


In [29]:
#16
matrix = np.random.random((3, 3))
row_sums = np.sum(matrix, axis=1)

column_vector = row_sums.reshape((-1, 1))
print(column_vector)

[[2.39494166]
 [2.03187594]
 [2.0634998 ]]


In [32]:
#17
matrix = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix)

print("Matrix:")
print(matrix)
print("Squared Matrix:")
print(squared_matrix)

Matrix:
[[ 5  4 10  8]
 [ 1  6 10  6]
 [ 3  8  4  5]]
Squared Matrix:
[[ 25  16 100  64]
 [  1  36 100  36]
 [  9  64  16  25]]


In [33]:
#18
vector = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(vector)

print("Vector:")
print(vector)
print("Square Root Vector:")
print(sqrt_vector)

Vector:
[28 42 30  8]
Square Root Vector:
[5.29150262 6.4807407  5.47722558 2.82842712]
